name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: 3.11
        architecture: x64 
    - name: Install dependencies
      run: pdm install
    - name: Build site
      run: pdm run pelican content
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'output.zip'
        directory: 'output'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: page-zip
    #     path: path/to/artifact/world.txt
